version: '3.8'

services:
  db:
    image: postgres:14
    container_name: weather-postgres
    environment:
      POSTGRES_DB: weather_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - weather_postgres_data:/var/lib/postgresql/data

volumes:
  weather_postgres_data:
